# Generated by Django 4.2.23 on 2026-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_loyalty_points_user_phone_loginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('merchant', 'Merchant'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
