# Generated by Django 4.2.23 on 2026-07-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sub_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='game',
            name='vendor_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
