# Generated by Django 4.2.23 on 2026-07-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('pinned', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Team Tiffany Gaming', max_length=150)),
                ('email', models.EmailField(default='support@teamtiffany.gg', max_length=254)),
                ('phone', models.CharField(default='+1 (555) 013-8888', max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('telegram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('address', models.CharField(default='Online — worldwide', max_length=255)),
                ('map_embed', models.TextField(blank=True, help_text='Google Maps iframe HTML')),
                ('about', models.TextField(default="Team Tiffany Gaming Casino brings you a curated collection of the world's most exciting games.")),
                ('terms', models.TextField(default='Play responsibly. 18+ only.')),
                ('privacy', models.TextField(default='We respect your privacy.')),
            ],
            options={
                'verbose_name_plural': 'Business Info',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(help_text='Page key, e.g. home, games, winners', max_length=60, unique=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('canonical', models.URLField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('robots', models.CharField(default='index, follow', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Team Tiffany Gaming Casino', max_length=120)),
                ('tagline', models.CharField(default='Play Premium. Win Big.', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('social_preview', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('color_primary', models.CharField(default='#0B0F1A', max_length=9)),
                ('color_secondary', models.CharField(default='#7C3AED', max_length=9)),
                ('color_accent', models.CharField(default='#F5C542', max_length=9)),
                ('currency', models.CharField(default='$', max_length=5)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('analytics_id', models.CharField(blank=True, max_length=40)),
                ('gsc_verification', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('game', models.CharField(blank=True, max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='winners/')),
                ('win_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-win_date', '-id'],
            },
        ),
    ]
