# Generated by Django 4.2.23 on 2026-07-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_promo_sitefaq_wallet_transaction_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='paid', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twilio_from',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twilio_token',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
