# Generated by Django 4.2.23 on 2026-07-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_cashout_status_sitesettings_twilio_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('load', 'Load / Deposit'), ('withdraw', 'Withdraw / Cashout')], default='load', max_length=10)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('platform_user_id', models.CharField(blank=True, max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=60)),
                ('order_id', models.CharField(blank=True, max_length=60)),
                ('platform_txn_id', models.CharField(blank=True, max_length=80)),
                ('agent_balance', models.CharField(blank=True, max_length=40)),
                ('user_balance', models.CharField(blank=True, max_length=40)),
                ('operator', models.CharField(blank=True, max_length=60)),
                ('shift', models.CharField(blank=True, max_length=20)),
                ('nepal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='game_api_agent_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='game_api_secret',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='game_api_url',
            field=models.CharField(blank=True, help_text='Base URL, e.g. https://host (no trailing /api)', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='operator',
            field=models.CharField(blank=True, help_text='Staff member who recorded it', max_length=60),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_txn_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shift',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
