# Generated by Django 4.2.23 on 2026-07-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_gametxn_sitesettings_game_api_agent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='game_api_force_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Optional: pin the API host to this IP', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='game_api_use_doh',
            field=models.BooleanField(default=True, help_text='Resolve the API host via secure DNS (DoH) to bypass ISP DNS blocking'),
        ),
    ]
