# Generated by Django 4.2.23 on 2026-07-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_sitesettings_game_api_force_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='signup_url',
            field=models.URLField(blank=True, default='https://www.facebook.com/profile.php?id=61572215053137'),
        ),
    ]
