# Generated by Django 4.2.23 on 2026-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_sitesettings_signup_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pay_api_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pay_api_url',
            field=models.CharField(blank=True, help_text='Gateway base URL, e.g. https://host', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pay_currency',
            field=models.CharField(default='usd', max_length=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pay_enabled_waycodes',
            field=models.CharField(default='cashapp,zelle,paypal,card,chime', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pay_max_amount',
            field=models.PositiveIntegerField(default=0, help_text='Cents, 0=none'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pay_mch_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pay_min_amount',
            field=models.PositiveIntegerField(default=0, help_text='Cents, 0=none'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pay_sign_type',
            field=models.CharField(default='MD5', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pay_transfer_waycodes',
            field=models.CharField(default='ecashapp,paypal,venmo,zelle,chime,card,ach', max_length=200),
        ),
    ]
