# Generated by Django 4.2.23 on 2026-07-12 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0, help_text="Total % fee on this merchant's orders", max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submerchants', to='payments.merchant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mch_order_no', models.CharField(max_length=64, unique=True)),
                ('transfer_order_no', models.CharField(blank=True, max_length=64)),
                ('amount', models.IntegerField(default=0, help_text='Cents')),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('way_code', models.CharField(blank=True, max_length=20)),
                ('way_param', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('state', models.IntegerField(choices=[(0, 'Created'), (1, 'In progress'), (2, 'Success'), (3, 'Failed'), (4, 'Revoked'), (6, 'Closed')], default=0)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('platform_amount', models.IntegerField(default=0)),
                ('parent_amount', models.IntegerField(default=0)),
                ('net_amount', models.IntegerField(default=0)),
                ('err_code', models.CharField(blank=True, max_length=40)),
                ('err_msg', models.CharField(blank=True, max_length=255)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success_time', models.BigIntegerField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_orders', to='payments.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mch_order_no', models.CharField(max_length=64, unique=True)),
                ('pay_order_no', models.CharField(blank=True, max_length=64)),
                ('amount', models.IntegerField(default=0, help_text='Cents')),
                ('real_amount', models.IntegerField(blank=True, help_text='Cents', null=True)),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('way_code', models.CharField(blank=True, max_length=20)),
                ('client_id', models.CharField(blank=True, max_length=64)),
                ('client_ip', models.CharField(blank=True, max_length=64)),
                ('state', models.IntegerField(choices=[(0, 'Created'), (1, 'In payment'), (2, 'Success'), (3, 'Failed'), (4, 'Revoked'), (5, 'Refunded'), (6, 'Closed'), (7, 'Disputed')], default=0)),
                ('cashier_url', models.CharField(blank=True, max_length=500)),
                ('expire_ts', models.BigIntegerField(blank=True, null=True)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('platform_amount', models.IntegerField(default=0, help_text='Cents (your cut)')),
                ('parent_amount', models.IntegerField(default=0, help_text='Cents (tier-1 margin)')),
                ('net_amount', models.IntegerField(default=0, help_text='Cents (originator keeps)')),
                ('ext_param', models.CharField(blank=True, max_length=512)),
                ('channel_order_no', models.CharField(blank=True, max_length=120)),
                ('err_code', models.CharField(blank=True, max_length=40)),
                ('err_msg', models.CharField(blank=True, max_length=255)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success_time', models.BigIntegerField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_orders', to='payments.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
